export enum FrameWorkErrorCode {
  ERR_FRAMEWORK_UNKNOWN = 'ERR_FRAMEWORK_UNKNOWN'
}

export enum RPCErrorCode {
  ERR_RPC_UNKNOWN = 'ERR_RPC_UNKNOWN',
  ERR_RPC_TIMEOUT = 'ERR_RPC_TIMEOUT',
  ERR_RPC_TUNNEL_NOT_AVAILABLE = 'ERR_RPC_TUNNEL_NOT_AVAILABLE'
}
